### ISSUE TITLE
Email body filter parameters may have changed in 1.4

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/edd-auto-register#111]
### Expected behavior
If a store has filtered the email body per our original example, which included the password in plain text, I expect that password in the email to still work.

### Actual behavior
For stores who had added a filter on the Auto Register email body, the password parameter in 1.4 seems to be different than it was in 1.3 (hashed vs. plain text). In 1.4, the password parameter is being retrieved from the user data, rather than the array of user args.

### Steps to reproduce the behavior
Add the following filter to your site:
```php
function my_child_theme_edd_auto_register_email_body( $default_email_body, $first_name, $username, $password ) {

	// Modify accordingly
	$default_email_body = __( "Dear", "edd-auto-register" ) . ' ' . $first_name . ",\n\n";
	$default_email_body .= __( "Below are your login details:", "edd-auto-register" ) . "\n\n";
	$default_email_body .= __( "Your Username:", "edd-auto-register" ) . ' ' . $username . "\n\n";
	$default_email_body .= __( "Your Password:", "edd-auto-register" ) . ' ' . $password . "\n\n";
	$default_email_body .= __( "Login:", "edd-auto-register" ) . ' ' . wp_login_url() . "\r\n";

	return $default_email_body;

}
add_filter( 'edd_auto_register_email_body', 'my_child_theme_edd_auto_register_email_body', 10, 4 );
```

Reportedly, the password parameter is different in 1.4 than it is in 1.3.x.

### Information:
PHP Version: 8.0
EDD Auto Register Version (or branch): master
EDD Version (or branch): 2.11.6
WordPress Version: 6.0

**Comment by mihaijoldis** [comment]
This would resolve the issue for users that are still using the old snippet but perhaps we should look at not allowing this in the future.

However, it was brought up to me by a user after asking them to use the new way (with the reset link) that they don't want the users to see the WordPress back end at all. I know there are other customers that don't want that too so perhaps at some point we should have the password reset/change feature in EDD Perhaps via a page with the [edd_login] short-code on.

```
The problem I have now is that this sets the user to reset his password in a WordPress context. (So the user clicks on the password reset link, then gets into the WordPress login and lands in the WordPress backend (where there is nothing to do for the user. And this usually ends up in emails like I accidentally logged into your site, I hope I didn't break anything")- Instead, I like the user not to land in their EDD account.
```
