### ISSUE TITLE
Auto-Register prevents Stripe checkout on EDD 3.0 

### ISSUE THREAD

**Issue by zackkatz** [awesomemotive/edd-auto-register#117]
I just sent in a bug report with a bunch of details; please refer there for more info and a full system report. 

**With auto-register de-activated, and in EDD 2.0 with the same plugins enabled, things work as expected.**

## With Auto-Register active:

1. Try to check out and an error shows up: `An error occurred, but your payment may have gone through. Please contact the site administrator.`
  - An order was created but marked as Pending
  - A subscription was created and set to active
2. Try to buy again; it says to refresh the page
3. Refresh the page
4. Check-out processes

This happens with 3DD and Stripe (Card deleted for screenshot but is valid):  
![Very unfortunate error](https://i.gravitykit.com/2dOvGR+)

### Notes

- All webhooks were successfully sent by Stripe and received by website. This is certain.
- EDDAR ran enough to get to `EDDAR: maybe_insert_user running...` and then print the payment object
- This error only happened on Stripe; PayPal worked fine

### Active EDD plugins & server stuff

Here's a list of EDD-related plugins I had running:

Easy Digital Downloads:   3.0.2.1
https://easydigitaldownloads.com

Easy Digital Downloads - Auto Register: 1.4.3
https://easydigitaldownloads.com/downloads/auto-register/

Easy Digital Downloads - Discounts Pro: 1.5.0
https://easydigitaldownloads.com/downloads/discounts-pro/

Easy Digital Downloads - Git Download Updater: 1.3
https://easydigitaldownloads.com/downloads/git-download-updater

Easy Digital Downloads - PayPal Website Payments Pro and PayPal Express Gateway: 1.4.6
https://sandhillsdev.com

Easy Digital Downloads - PDF Invoices: 2.2.29
https://sandhillsdev.com/

Easy Digital Downloads - Per Product Emails: 1.1.8
https://easydigitaldownloads.com/downloads/per-product-emails/

Easy Digital Downloads - Recurring Payments: 2.11.7
https://easydigitaldownloads.com/downloads/edd-recurring/

Easy Digital Downloads - Remove Subscriptions for German Customers: 1.0
Easy Digital Downloads

Easy Digital Downloads - Software Licensing: 3.8.6
https://easydigitaldownloads.com/downloads/software-licensing/

Easy Digital Downloads - Stripe Payment Gateway: 2.8.1
https://sandhillsdev.com

Easy Digital Downloads - User Switching: 1.0
https://github.com/easydigitaldownloads/library

Easy Digital Downloads - Variable Pricing Switcher: 1.0.5
http://www.barrykooij.com/edd-checkout-variable-pricing-switcher

Easy Digital Downloads - Zapier: 1.3.11
https://easydigitaldownloads.com/downloads/zapier/

Easy Digital Downloads integration for Help Scout: 2.2.0
https://webgilde.com

Easy Digital Downloads Putler Connector: 2.5.8.1
http://putler.com/connector/edd/

Easy Digital Downloads Toolbar: 1.5.1
http://genesisthemes.de/en/wp-plugins/edd-toolbar/

Easy Digital Downloads — Validate gravity+ Discount Code: 1.0.0
https://gravityplus.pro

-- Webserver Configuration

PHP Version:              7.4.15
MySQL Version:            8.0.23
Webserver Info:           nginx/1.18.0

-- PHP Configuration

Memory Limit:             5120M
Upload Max Size:          64M
Post Max Size:            64M
Upload Max Filesize:      64M
Time Limit:               30
Max Input Vars:           1000
Display Errors:           N/A
PHP Arg Separator:        &

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Disabled

### End System Info ###

**Comment by cklosowski** [comment]
@zackkatz I noticed your not on the latest Stripe:
Easy Digital Downloads - Stripe Payment Gateway: 2.8.1
https://sandhillsdev.com/

Our latest is 2.8.11. Can you please try updating Stripe possibly by manually updating it after downloading it from [your account](https://easydigitaldownloads.com/your-account/your-downloads)?

**Comment by zackkatz** [comment]
@cklosowski I meant to update this ticket yesterday; upgrading Stripe fixed the issue. The update wasn’t appearing for some reason. Thanks!
