### ISSUE TITLE
When logged in, updating email address on checkout creates a new account

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/edd-auto-register#119]
### Expected behavior
If updating email address on checkout, new email should should be added to the current customer and no new user account should be created.

### Actual behavior
If email address is changed on checkout a new WP user account and customer is created.

### Steps to reproduce the behavior
1) Be logged in as an existing customer
2) Add a recurring product (recurring may or may not be relevant) to cart
3) Complete purchase, user account should not change.

### Information:
PHP Version: 7

EDD Auto Register Version (or branch): 1.4.3

EDD Version (or branch): 2.11 and 3.0.3

WordPress Version: 6

Any other relevant information:
Auto Register `1.3.14` doesn't have this issue so this appears to have started in `1.4`.

**Comment by dgoldak** [comment]
This doesn't happen with a one time purchase so it requires Recurring Payments + Auto Register.

I downgraded Recurring as far back as 2.10.6 and still experience this issue with Auto Register 1.4.3.

**Comment by cklosowski** [comment]
We've identified that the new customer is coming from a combination of Stripe + EDD and has nothing to do with Auto Register.
