### ISSUE TITLE
Option to send login credentials in first purchase receipt

### ISSUE THREAD

**Issue by amdrew** [awesomemotive/edd-auto-register#13]
Currently the login and password is sent in a separate email. It would be nice to have an option so this is included in the purchase receipt.

**Comment by mindctrl** [comment]
@sumobi customer requested ability to disable the password being sent and instead send a link for customers to set the password, like WP core does now. Have any thoughts about that?

**Comment by sumobi** [comment]
@mindctrl :+1: to that

**Comment by grappler** [comment]
I am working on this. How would you check if it the first purchase?

**Comment by pippinsplugins** [comment]
@grappler Instantiate [EDD_Customer](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-customer.php) and then look to see if there's just one payment ID in the `payment_ids` property.

**Comment by sumobi** [comment]
:+1: Will give it a test

**Comment by grappler** [comment]
When is the next planned time to check the open PRs? :smile: :

**Comment by pippinsplugins** [comment]
@grappler Whoops, sorry, missed this. Just left you a comment on the PR.

**Comment by flowdee** [comment]
This would be great!

**Comment by grappler** [comment]
@flowdee Could you test the PR https://github.com/easydigitaldownloads/edd-auto-register/issues/24?
