### ISSUE TITLE
Make Auto Register work for CSV Payment Imports

### ISSUE THREAD

**Issue by mintplugins** [awesomemotive/edd-auto-register#33]
People who are migrating payments from 1 domain to another will likely want to have their users migrated as well. A good way to do this would be to have Auto Register create the WordPress users when the payments are created during the CSV import. 

However, currently, it does not create the users upon CSV import because of these 2 things:

https://github.com/easydigitaldownloads/edd-auto-register/blob/9806021e969d211a339aff70dfa53eec963971a9/edd-auto-register.php#L293

https://github.com/easydigitaldownloads/edd-auto-register/blob/master/edd-auto-register.php#L314

Proposal: Make Users get Auto Registered when creating payments if it is being done through CSV Payment Import

**Comment by SDavisMedia** [comment]
@pippinsplugins Auto Register is working for me on import but it seems to trigger the account verification process no matter what, sending the customer an email about verification. That seems odd. The payment being imported is a guest purchase from the old site.

**Comment by pippinsplugins** [comment]
@SDavisMedia not intentional.

**Comment by robincornett** [comment]
Another one that I thought had already been reopened as the work was started fresh in #86.
