### ISSUE TITLE
Make Auto Register work for Manual Purchases

### ISSUE THREAD

**Issue by mintplugins** [awesomemotive/edd-auto-register#37]
When creating a Payment through Manual Purchases, no WordPress user is generated if no corresponding user exists.

Proposal: If they don't yet exist, make new WordPress user for customers created through Manual Purchases.

**Comment by mintplugins** [comment]
This was fixed here:
https://github.com/easydigitaldownloads/edd-manual-purchases/issues/62

**Comment by robincornett** [comment]
Reopening as we need to address this for EDD 3.0, outside of the manual purchases extension. In 3.0, manual orders are added with the `edd_add_manual_order` function on the `edd_add_order` hook. Unfortunately, there are no hooks within that function--need to see if we need to adjust something in core, or if there is a different moment in the process where auto register can hook in.
