### ISSUE TITLE
Lacks a small icon for the WP Directory

### ISSUE THREAD

**Issue by zackkatz** [awesomemotive/edd-auto-register#38]
<img width="394" alt="screen shot 2017-01-03 at 5 20 07 pm" src="https://cloud.githubusercontent.com/assets/870979/21627956/f062dae4-d1d8-11e6-9375-095ff57e802c.png">

**Comment by sumobi** [comment]
Thanks @zackkatz, I'll hit this one and all the EDD ones after AffiliateWP. Currently working my way through RCP. Turns out we have quite a few add-ons.
