### ISSUE TITLE
Save address to user meta after checkout

### ISSUE THREAD

**Issue by SDavisMedia** [awesomemotive/edd-auto-register#45]
When manually registering at checkout with just EDD core (so no Auto Register), and an address is provided (like with taxes enabled), `_edd_user_address` is saved to the user meta.

When Auto Register is used to register that user, `_edd_user_address` is not created. It doesn't appear that the data is saved anywhere at all.

**Comment by pippinsplugins** [comment]
@sunnyratilal could you tackle this?

**Comment by sunnyratilal** [comment]
As per #33, this will need updating before it is merged.

I'll work on getting #33 refreshed first (there's a merge conflict) and then refresh this PR.

**Comment by pippinsplugins** [comment]
@sunnyratilal PR looks good. Let us know when you're ready with #33 so we can get both merged.

**Comment by SDavisMedia** [comment]
Tested and working for me as well.

**Comment by robincornett** [comment]
This issue should have been reopened as #87 was a fresh start on implementing. Reopening as that needs to be finalized.
