### ISSUE TITLE
Grey out Guest Checkout setting with explanation about why it's disabled

### ISSUE THREAD

**Issue by mintplugins** [awesomemotive/edd-auto-register#47]
Currently, Guest Checkout mode is required if you have the Auto Register extension activated. You cannot check the box that says "Require Logins", it does not save. 

Even though you have it checked, when you hit save, the page refreshes with the box being unchecked - and gives you no explanation of why. It looks like saving the setting is broken. 

This goes for the "Show Register/Login Form" setting as well. That change was introduced here:
https://github.com/easydigitaldownloads/edd-auto-register/pull/18/files

If "Login Form Only" and "None" are going to be the only available options, that should be indicated somehow. Possibly, the non-available options should be greyed out and disabled with an explanation of why. Otherwise the user has no other choice but to assume their saving of settings is broken. It has lead to more than 1 wild goose chase in support.

**Comment by dgoldak** [comment]
+1 for this feature. Recent ticket raised confusion about Guest Checkout while using Auto Register.
https://secure.helpscout.net/conversation/963850925/132464?folderId=1847242

If nothing changes, we should at least gray out Guest Checkout since it's not currently utilized while Auto Register is enabled.

**Comment by mihaijoldis** [comment]
First time I see this issue but +25 for it. I had plenty of tickets with users complaining that the Guest Checkout setting is broken and its not saving.
Most recent one https://secure.helpscout.net/conversation/1413766505/176545/

**Comment by mihaijoldis** [comment]
I wanted to bump this as it should reduce quite a few support tickets.
Along with the gues checkout not saving we should also adjust the Show Register / Login form too as that will not let you select anything other than Login form only or None when AR is activated.

We could grey out the `Require Login` setting and add a description explaining why and also in the `Show Register / Login` we could either add a description of why you can't select all options or perhaps remove those 2 options from the selector.

**Comment by mihaijoldis** [comment]
Just had a new customer confused about this
