### ISSUE TITLE
Cannot save Checkout Fields Manager data as user meta with Auto Register activated

### ISSUE THREAD

**Issue by SDavisMedia** [awesomemotive/edd-auto-register#62]
## Bug Report
Auto Register and Checkout Fields Manager conflict in that Auto Register makes Checkout Fields Manager believe that a purchase is being made by a true guest, when in reality Auto Register is creating a user account... so it's not really a guest.

### Expected behavior
Given the above statement, Checkout Fields Manager should be able to save custom fields to EITHER user meta or payment meta using the `Where should this meta be stored` setting built into each field of the Checkout Fields Manager form builder.

### Actual behavior
The ability to choose whether a field is saved as user meta or payment meta is removed in Checkout Fields Manager, and data is forced to save as payment meta, because Auto Register makes Checkout Fields Manager think that EDD is allowing guest checkouts.

### Steps to reproduce the behavior
1) Activate both Auto Register and Checkout Fields Manager
2) Set `WP_DEBUG` to `false` if it is `true`. Reason being, the Checkout Fields Manager `Where should this meta be stored` field will always show when `WP_DEBUG` is set to `true`.
3) Create a NEW field on your Checkout Fields Manager checkout form. You will see that there is no option for choosing how to save the field data.
4) Complete a test purchase while logged out and observe the fact that the custom data was forced to be saved as payment data.

### Information:
EDD Auto Register Version (or branch): `master`
Checkout Fields Manager: `master`
EDD Version (or branch): `master`

### Any other relevant information:
When Auto Register is activated, let's allow the Checkout Fields Manager `Where should this meta be stored` option to be displayed, giving the site admin the choice to save data to user meta, since a new user is being created.

**Comment by cklosowski** [comment]
Initial looking over the code for Auto Register, the guest checkout filters are being run on both admin _and_ front end. I think initially we could try for the quick fix of only allowing these filters to apply when it's `! is_admin()`, since in reality the goal of Auto Register is to remove a set of inputs and items from the checkout since Auto Register will be automatically handling those during processing the purchase, which only affects the front end. and not admin.

**Comment by cklosowski** [comment]
I'm punting this so we can look at getting 1.3.11 out soonish.

**Comment by dgoldak** [comment]
Customer running into this bug:
https://secure.helpscout.net/conversation/1050201518/141690?folderId=1847242

**Comment by robincornett** [comment]
Closing as we've fixed it in the Checkout Fields Manager extension: https://github.com/awesomemotive/edd-checkout-fields/issues/204, version 2.1.9 (released October 2021).
