### ISSUE TITLE
Disable auto register for specific product

### ISSUE THREAD

**Issue by Shinckey** [awesomemotive/edd-auto-register#74]
## Bug Report

Hello, I want use Auto register only for specific product. 
For example I want it for online courses, but not for vouchers.

I tried your code here:
https://github.com/easydigitaldownloads/edd-auto-register/pull/23/commits/0c2dc855b93ae6dbbc038c14d296c1e81da54f1e
But it doesnt work. EDD support wrote me:"Unfortunately we discovered that code no longer works and there is not a simple fix for it."
My question is: Can you fix it, please? :-)

**Comment by robincornett** [comment]
Confirmed the code example does not work. The example is hooked into `init`, so runs after the auto register filter. However, the auto register filter is run so early (on `plugins_loaded`) that I'm finding it's impossible to modify the filter conditionally.

I think it would be worth registering a new filter, something like `edd_auto_register_can_create_user`, and extract all of the boolean logic at the beginning of `create_user` into a new method, the result of which is run through this filter. Then disabling auto register for a specific product would be straightforward and would have access to existing payment data.
